"""Build the skill's synalog references from synalog's own skill.

skills/semantic-layers/references/synalog.md and errors.md are generated:
a layer-specific part (shell/skill/) followed by sections of synalog's
skill (../synalog/skills/synalog/SKILL.md), so the language is written in
one place. Run after synalog's skill changes:

    uv run python shell/sync_skill.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYNALOG_SKILL = ROOT.parent / "synalog" / "skills" / "synalog" / "SKILL.md"
EXAMPLES_URL = "https://github.com/SynaLinks/synalog/blob/main/skills/synalog/examples/"
REFERENCES = ROOT / "skills" / "semantic-layers" / "references"

#: synalog skill sections in each generated file, by heading.
LANGUAGE = [
    "Critical rules",
    "Syntax",
    "Aggregation (in the rule head, with `distinct`)",
    "Built-in functions",
    "Temporal columns: mandatory pipeline",
    "Recursion",
    "Functors (parameterize predicates)",
    "Knowledge graphs",
]
ERRORS = ["Reading errors"]


def sections(text: str) -> dict[str, str]:
    """Level-2 sections of a markdown document, by heading (bodies keep
    their level-3 subsections)."""
    parts = re.split(r"^## (.+)$", text, flags=re.M)
    return {parts[i].strip(): parts[i + 1].strip() for i in range(1, len(parts), 2)}


def generated(head: str, skill: str, names: list[str]) -> str:
    found = sections(skill)
    missing = [n for n in names if n not in found]
    if missing:
        raise SystemExit(f"synalog's skill has no section {', '.join(missing)}")
    body = []
    for name in names:
        text = found[name].replace("](examples/", f"]({EXAMPLES_URL}")
        body.append(f"## {name}\n\n{text}\n")
    note = "<!-- Generated by shell/sync_skill.py from synalog's skill: edit there, then rerun. -->\n\n"
    return head.rstrip() + "\n\n" + note + "\n".join(body)


def build() -> dict[Path, str]:
    skill = SYNALOG_SKILL.read_text()
    layer = (ROOT / "shell" / "skill" / "synalog-in-a-layer.md").read_text()
    errors = (ROOT / "shell" / "skill" / "layer-errors.md").read_text()
    return {
        REFERENCES / "synalog.md": generated(layer, skill, LANGUAGE),
        REFERENCES / "errors.md": generated(errors, skill, ERRORS).replace("## Reading errors\n\n", "## synalog's\n\n", 1),
    }


if __name__ == "__main__":
    if not SYNALOG_SKILL.exists():
        sys.exit(f"{SYNALOG_SKILL} not found: check synalog out beside this repository")
    for path, text in build().items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
