"""Connecting a layer: layer.toml, the secrets in .env, the tables."""

import stat
import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib

import pytest
from samples import PG, write

from semantic_layers import connect
from semantic_layers.layers import verify


def test_connect_generates_tables_and_keeps_descriptions(tmp_path):
    layer = tmp_path / "shop"
    write(
        layer,
        {
            "tables/PublicOrders.l": "---\nname: PublicOrders\ndescription: One row per order.\n---\nPublicOrders(id:) :- public.orders(id:);\n"
        },
    )
    seen = []

    def fake(engine, connection):
        seen.append((engine, connection))
        return (
            "# Tables — generated by `synalog introspect psql` (2 tables).\n"
            "PublicOrders(id:, status:) :- public.orders(id:, status:);\n"
            "PublicCustomers(id:) :- public.customers(id:);\n"
        )

    connect.write_connection(layer, "psql", {**PG, "password": "p@ss/word"})
    result = connect.generate_tables(layer, introspect=fake)
    ((engine, conn),) = seen
    assert engine == "psql" and conn == {
        "engine": "psql",
        "host": "h",
        "port": 5432,
        "database": "db",
        "user": "u",
        "password": "p@ss/word",
        "sslmode": "prefer",
        "schema": "public",
    }
    assert result["written"] == ["PublicCustomers", "PublicOrders"]
    orders = (layer / "tables" / "PublicOrders.l").read_text()
    assert "description: One row per order." in orders and "status:" in orders
    conn = tomllib.loads((layer / "layer.toml").read_text())["connection"]
    assert conn == {
        "engine": "psql",
        "host": "h",
        "port": 5432,
        "database": "db",
        "user": "u",
        "sslmode": "prefer",
        "schema": "public",
    }  # no secret in the committed file
    assert stat.S_IMODE((layer / ".env").stat().st_mode) == 0o600
    assert (layer / ".env").read_text() == 'SYNALOG_PSQL_PASSWORD="p@ss/word"\n'
    assert ".env" in (layer / ".gitignore").read_text().splitlines()
    assert verify(layer) == []


def test_connect_refuses_local_engines(tmp_path):
    with pytest.raises(ValueError, match="in memory"):
        connect.write_connection(tmp_path, "duckdb", {})
    with pytest.raises(ValueError, match="no field hots"):
        connect.write_connection(tmp_path, "psql", {**PG, "hots": "x"})
    with pytest.raises(ValueError, match="needs database"):
        connect.write_connection(tmp_path, "psql", {"host": "h", "user": "u"})


def test_connect_keeps_the_gitignore(tmp_path):
    from semantic_layers.init import init

    init(tmp_path / "shop", description="Orders of the shop.")
    (tmp_path / "shop" / ".gitignore").write_text("*.csv\n")
    connect.write_connection(tmp_path / "shop", "psql", PG)
    assert (tmp_path / "shop" / ".gitignore").read_text() == "*.csv\n.env\nbigquery-credentials.json\n"


def test_connect_keeps_other_env_lines(tmp_path):
    (tmp_path / ".env").write_text("OTHER=1\nSYNALOG_PSQL_PASSWORD=old\n")
    connect.write_connection(tmp_path, "psql", PG)
    assert (tmp_path / ".env").read_text() == 'OTHER=1\nSYNALOG_PSQL_PASSWORD="p"\n'
    assert connect.layer_connection(tmp_path)["password"] == "p"


def test_a_secret_keeps_its_quotes(tmp_path):
    connect.write_connection(tmp_path, "psql", {**PG, "password": '"quoted"'})
    assert connect.layer_connection(tmp_path)["password"] == '"quoted"'


def test_connect_keeps_the_project_table(tmp_path):
    from semantic_layers.init import init

    init(tmp_path / "shop", description="Orders of the shop.")
    connect.write_connection(tmp_path / "shop", "psql", PG)
    data = tomllib.loads((tmp_path / "shop" / "layer.toml").read_text())
    assert data["project"] == {"name": "shop", "description": "Orders of the shop."}
    assert data["connection"]["host"] == "h"
