"""``semantic-layers init``: set up a semantic layer project.

A layer project is a layer folder ready to be filled and published: the
three folders, a ``synalog.toml`` for the database it runs on, the
``.gitignore`` that keeps the secrets (``.env``) out of git, a README for whoever
installs it, and a git repository — pushed, it is a one-layer repository
that ``semantic-layers add owner/repo`` installs.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

from synalog import project

from .connect import PROJECT_FILE, SECRET_FILES, project_template
from .layers import FOLDERS

#: Layer names: lowercase letters, numbers and single hyphens, as Agent Skills'.
_NAME = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")


def readme(name: str) -> str:
    return f"""# {name}

A [semantic layer](https://github.com/SynaLinks/semantic-layers): business
definitions about one database, as verified, executable
[synalog](https://github.com/SynaLinks/synalog) `.l` files.

| Folder | Holds |
|---|---|
| `tables/` | the data: one file per table, generated by `semantic-layers connect` |
| `concepts/` | what the data is about: entities, relationships, clean views |
| `rules/` | what you want to know: counts, rates, rankings, trends |

## Install

```shell
uvx semantic-layers add <owner>/{name}
cd .agents/layers/{name}
uvx semantic-layers connect                      # the database in its synalog.toml
uvx semantic-layers connect <engine> key=value ...  # or another one
```

## Develop

```shell
uvx semantic-layers connect <engine> key=value ...     # synalog.toml, .env, then tables/ from the database
uvx synalog rules/<Name>.l run <Name>                   # run a definition
uvx semantic-layers check .                                      # verify every definition
```
"""


def init(target: Path, name: str | None = None, description: str = "") -> dict:
    """Set up the layer project ``target`` (created if missing). Never
    overwrites a file that exists. Returns what was ``created``."""
    name = name or target.resolve().name
    if not description.strip():
        raise ValueError("a layer needs a description: what it is about, for whoever installs it.")
    if not _NAME.match(name):
        raise ValueError(
            f"'{name}' is not a layer name: use lowercase letters, numbers and hyphens "
            "(e.g. sales, customer-retention)."
        )
    if target.exists() and not target.is_dir():
        raise ValueError(f"{target} is a file.")
    created: list[str] = []
    target.mkdir(parents=True, exist_ok=True)
    for folder in FOLDERS.values():
        path = target / folder
        if not path.exists():
            path.mkdir()
            (path / ".gitkeep").touch()
            created.append(f"{folder}/")
    for relative, text in ((PROJECT_FILE, project_template(name, description)), ("README.md", readme(name))):
        path = target / relative
        if not path.exists():
            path.write_text(text)
            created.append(relative)
    if not (target / ".gitignore").exists():
        created.append(".gitignore")
    project.ensure_gitignore(target)
    if not _in_git_repo(target):
        subprocess.run(["git", "init", "-q", str(target)], check=False, capture_output=True)
        if _in_git_repo(target):
            created.append(".git/")
    return {"name": name, "path": str(target), "created": created, "secrets": list(SECRET_FILES)}


def _in_git_repo(path: Path) -> bool:
    result = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "--is-inside-work-tree"],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode == 0 and result.stdout.strip() == "true"
